#!/bin/bash
# Rebuilds save-states.js from every *.txt file in this directory.
# Each .txt file (the raw JSON output of genePool.getPoolData()) becomes
# an entry in window.POOL_SNAPSHOTS, keyed by its filename minus the
# .txt extension. Re-run this after adding or editing a snapshot.
#
# Usage:  ./save-states/rebuild.sh
# Output: save-states/save-states.js  (loaded by index.html at boot)

set -e
cd "$(dirname "$0")"

OUT="save-states.js"

{
    echo "// Auto-generated by save-states/rebuild.sh — do not edit by hand."
    echo "// To regenerate: run ./save-states/rebuild.sh from the project root."
    echo "window.POOL_SNAPSHOTS = {"

    first=1
    for f in *.txt; do
        [ -e "$f" ] || continue
        name="${f%.txt}"
        if [ $first -eq 0 ]; then
            echo ","
        fi
        printf '  "%s": ' "$name"
        cat "$f"
        first=0
    done

    echo ""
    echo "};"
} > "$OUT"

count=$(ls *.txt 2>/dev/null | wc -l | tr -d ' ')
echo "Wrote save-states/$OUT with $count snapshot(s)."
